# Database Configuration
database:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: password
  table-prefix: walletlogin_

# Plugin Settings
settings:
  require-login: true  # If true, players must login to play
  require-wallet-login: false  # If true, players must connect a wallet to play
  login-timeout: 60  # Time in seconds for players to login after joining
  session-timeout: 1440  # Time in minutes for session to expire (24 hours)
  max-login-attempts: 5  # Maximum number of login attempts before timeout
  login-attempt-timeout: 10  # Time in minutes for login attempt timeout
  register-ip-limit: 3  # Maximum number of accounts per IP
  wallet-validation: true  # Whether to validate wallet addresses format
  solana-only: true  # Only allow Solana wallets

# Authentication Settings
auth:
  min-password-length: 6  # Minimum password length
  max-password-length: 32  # Maximum password length
  hash-algorithm: "PBKDF2WithHmacSHA256"  # Password hashing algorithm
  hash-iterations: 65536  # Number of iterations for password hashing
  hash-key-length: 256  # Key length for password hashing
  salt-length: 16  # Salt length for password hashing

# Solana Settings
solana:
  network: "devnet"  # mainnet, testnet, or devnet
  rpc-url: "https://api.devnet.solana.com"  # RPC URL for Solana network
  verification-message: "I confirm that I own this wallet and authorize its use on the Minecraft server."  # Message to sign for verification

# Web Server Settings
web-server:
  enabled: true  # Whether to enable the web server for QR code login
  url: "http://localhost:3000"  # URL of the web server
  port: 3000  # Port of the web server
  qr-code-timeout: 300  # Time in seconds for QR code to expire (5 minutes)
  check-interval: 5  # Time in seconds to check for wallet connection status

# Messages
messages:
  prefix: "&8[&6SolanaLogin&8] &r"
  # Login/Register Messages
  login-required: "&cPlease login with /login <password>"
  register-required: "&cPlease register with /register <password> <confirmPassword>"
  login-success: "&aYou have successfully logged in!"
  login-fail: "&cIncorrect password! Attempts remaining: %attempts%"
  login-timeout: "&cYou took too long to login. Please reconnect."
  login-attempts-exceeded: "&cToo many failed login attempts. Please try again later."
  register-success: "&aYou have successfully registered! Please login with /login <password>"
  register-fail: "&cRegistration failed. Please try again."
  register-password-mismatch: "&cPasswords do not match!"
  register-password-too-short: "&cPassword is too short! Minimum length: %length%"
  register-password-too-long: "&cPassword is too long! Maximum length: %length%"
  register-ip-limit: "&cYou have reached the maximum number of accounts for your IP!"
  already-logged-in: "&cYou are already logged in!"
  already-registered: "&cYou are already registered!"
  not-logged-in: "&cYou must be logged in to use this command!"

  # Wallet Messages
  wallet-connected: "&aYour Solana wallet has been successfully connected!"
  wallet-disconnected: "&cYour Solana wallet has been disconnected."
  wallet-required: "&cYou need to connect a Solana wallet to play on this server. Use /connectwallet <address>"
  invalid-wallet: "&cThe wallet address you provided is not a valid Solana address."
  already-connected: "&cYou already have a wallet connected. Use /disconnectwallet first."
  not-connected: "&cYou don't have a wallet connected."
  wallet-info: "&aYour connected Solana wallet is: &6%wallet%"
  wallet-verification-required: "&cYou need to verify your wallet ownership. Please check the website or use /verifycode <code>"
  wallet-verification-success: "&aYour wallet has been successfully verified!"
  wallet-verification-fail: "&cWallet verification failed. Please try again."
  wallet-verification-pending: "&eYour wallet verification is pending. Please complete the verification process."
