name: SolanaLogin
version: '${project.version}'
main: com.nftlogin.walletlogin.SolanaLogin
api-version: '1.18'
api: '4.0.0'
authors: [NFTLogin]
description: A plugin that integrates Minecraft login with Solana wallet connection
commands:
  # Authentication commands
  register:
    description: Register an account
    usage: /register <password> <confirmPassword>
    permission: solanalogin.register
  login:
    description: Login to your account
    usage: /login <password>
    permission: solanalogin.login
  changepassword:
    description: Change your password
    usage: /changepassword <oldPassword> <newPassword> <confirmNewPassword>
    permission: solanalogin.changepassword
  logout:
    description: Logout from your account
    usage: /logout
    permission: solanalogin.logout

  # Wallet commands
  connectwallet:
    description: Connect your Solana wallet to your Minecraft account
    usage: /connectwallet or /connectwallet qr
    permission: solanalogin.wallet.connect
  disconnectwallet:
    description: Disconnect your Solana wallet from your Minecraft account
    usage: /disconnectwallet
    permission: solanalogin.wallet.disconnect
  walletinfo:
    description: View your Solana wallet information
    usage: /walletinfo
    permission: solanalogin.wallet.info

  # Admin commands
  solanalogin:
    description: Admin commands for SolanaLogin
    usage: /solanalogin <reload|info>
    permission: solanalogin.admin

permissions:
  # Authentication permissions
  solanalogin.register:
    description: Allows players to register an account
    default: true
  solanalogin.login:
    description: Allows players to login to their account
    default: true
  solanalogin.changepassword:
    description: Allows players to change their password
    default: true
  solanalogin.logout:
    description: Allows players to logout from their account
    default: true

  # Wallet permissions
  solanalogin.wallet.connect:
    description: Allows players to connect their Solana wallet
    default: true
  solanalogin.wallet.disconnect:
    description: Allows players to disconnect their Solana wallet
    default: true
  solanalogin.wallet.info:
    description: Allows players to view their Solana wallet information
    default: true
  solanalogin.wallet.verify:
    description: Allows players to verify their Solana wallet
    default: true

  # Admin permissions
  solanalogin.admin:
    description: Allows access to admin commands
    default: op
